schemaVersion: 2.2.0
components:
  - name: gitlab-docs
    attributes:
      gl/inject-editor: true
    container:
      image: registry.gitlab.com/gitlab-org/gitlab-docs:workspace
      env:
        - name: SEARCH_BACKEND
          value: lunr
      endpoints:
        - name: docs
          targetPort: 3000
          secure: true
          protocol: http
