root: true
extends:
  - 'plugin:@gitlab/default'
env:
  jest: true
parserOptions:
  parser: '@babel/eslint-parser'
  import/no-extraneous-dependencies: false
plugins:
  - 'filenames'
rules:
  filenames/match-regex:
    - error
    - "^[a-z0-9_]+(\\.config|\\.[a-z_]+\\_spec)?$"
  import/no-unresolved:
    - error
    # Ignoring glob for now:
    # https://github.com/import-js/eslint-plugin-import/issues/2703
    # https://github.com/import-js/eslint-plugin-import/issues/2883
    - ignore:
        - 'glob'
