image: registry.gitlab.com/gitlab-org/gitlab-docs/lint-html:alpine-3.14-ruby-2.7.4-8d8b30eb

ports:
  - port: 3004
    onOpen: open-browser

tasks:
  - init: |
      bundle install
      yarn install --frozen-lockfile
      bundle exec rake
      bundle exec nanoc compile
    command: bundle exec nanoc live --port=3004
