---
image:
  file: .gitpod.Dockerfile

ports:
  - port: 3004
    onOpen: open-browser

tasks:
  - init: |
      make install-ruby-dependencies
      make install-nodejs-dependencies
      bundle exec rake
      make compile
    command: bundle exec nanoc live --port=3004
